import type { VisibleModuleDefinition } from '../../../contracts/InteractiveModule';
import { GeometryMotionModule, type GeometryFamilyId } from './GeometryMotionModule';
import './GeometryMotionCovers';

function defineGeometryFamily(
    id: GeometryFamilyId,
    title: string,
    description: string,
    subtitle: string,
    cover: string,
    order: number,
): VisibleModuleDefinition {
    return {
        id: `mathematics-${id}`,
        title,
        description,
        category: 'mathematics',
        labId: 'mathematics',
        catalog: { subtitle, cover },
        tags: ['geometry', '2d', 'continuous-animation', 'invariants'],
        capabilities: ['pause', 'reset'],
        status: 'ready',
        order,
        create: () => new GeometryMotionModule(id),
    };
}

export const triangleMotionDefinition = defineGeometryFamily(
    'triangle-motion',
    'Triangle Motion',
    'Continuously animated triangle centers, circles and invariant lines.',
    'centers · circles · lines that stay true',
    'geometry-triangle-motion',
    10,
);

export const circleMotionDefinition = defineGeometryFamily(
    'circle-motion',
    'Circle Geometry',
    'Continuously animated chord power, tangency, radical axes and inversion.',
    'chords · tangency · inversion',
    'geometry-circle-motion',
    20,
);

export const motionCurvesDefinition = defineGeometryFamily(
    'motion-curves',
    'Motion Curves',
    'Curves generated by harmonic motion and rolling circles.',
    'rolling circles · harmonic traces',
    'geometry-motion-curves',
    30,
);
