import type { DemoDefinition } from '../../types';

export const blenderFibonacciMetadata: Omit<DemoDefinition, 'Component'> = {
  id: '001-blender-fibonacci',
  title: 'AI Blender: Golden Galaxy Vortex',
  description: 'A deep 3D vortex generated by a Blender Python script using the Golden Ratio (Fibonacci). Features a dynamic cascading animation where particles plunge into the gravity well from the outer rim.',
  route: '/blender-fibonacci',
  tags: ['Blender', 'glTF', 'AI-Pipeline', 'Math', 'Animation', 'Galaxy'],
  instructions: [
    'Drag to orbit around the model',
    'Scroll to zoom in/out',
    'Use the Leva Control Panel (top right) to adjust animation speed, pause/resume, and reset camera.',
  ],
};
